{% set version = "0.8.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set cran_mirror = 'https://cran.r-project.org' %}

package:
  name: r-clustermq
  version: {{ version|replace("-", "_") }}

source:
  fn: clustermq_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/clustermq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clustermq/clustermq_{{ version }}.tar.gz
  sha256: a46a89b50eeb542964e834e87e57c993dc790434eecc870fbaccf3d41f224a2b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-r6
    - r-infuser >=0.2.8
    - r-narray
    - r-progress
    - r-purrr
    - r-rzmq >=0.9.3
  run:
    - r-base
    - r-r6
    - r-infuser >=0.2.8
    - r-narray
    - r-progress
    - r-purrr
    - r-rzmq >=0.9.3

test:
  commands:
    - $R -e "library('clustermq')"           # [not win]
    - "\"%R%\" -e \"library('clustermq')\""  # [win]

about:
  home: https://github.com/mschubert/clustermq
  license: Apache 2.0
  summary: Evaluate arbitrary function calls using workers on HPC schedulers in single line of
    code. All processing is done on the network without accessing the file system. Remote
    schedulers are supported via SSH.
  license_family: APACHE

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
