{% set version = "0.9.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clustermq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clustermq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clustermq/clustermq_{{ version }}.tar.gz
  sha256: dd7c4ca4fa96c985d637f98e3dfbad38fd165b5ea802ddaafd6ac6fd0bc5c415

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - zeromq                       # [not win]
    - r-base
    - r-r6
    - r-rcpp
    - r-narray
    - r-progress
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-r6
    - r-rcpp
    - r-narray
    - r-progress

test:
  requires:
    - r-testthat
    - r-foreach
    - r-dplyr
  source_files:
    - tests/
  commands:
    - $R -e "library('clustermq')"                                           # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('clustermq')\""                                           # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://github.com/mschubert/clustermq
  license: Apache-2.0
  summary: Evaluate arbitrary function calls using workers on HPC schedulers in single line of code. All processing is done on the network without accessing the file system. Remote schedulers are supported via SSH.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
