appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: zwvP+FDkBCAZN8ZzGFBCTkNSYn1lPWBW1RFX6un0E4p/hH+LVCx07x22R9S2HGumcSfrTT9Ay5ZCikOm3GroXZY+MRuRMcSHG0RhhZ3Ybhs3q5PqtAEH4EMO2oI6VPDt406hqN1C2gLQ8NisX+dKP3SRT6X1X6WPuuFZurznRAaeO82cBQ/Q4JQAu427vi/I1g34476qXr3DcovFsvPRPZdLfXlKPSAw5guo36VIRQIiOVK+7QouY7vO9bPOhxFsQEEkVFViB0QKeFSLxvVbnUCDACo6s5fldZJQCwU/OU8f8cfAMfUR3/M8McuqFSLZv6Gzt2fiOzQXygNZCSBTYB7JyvBa+uWDuloaDTJ6c9gSSwwpaivcoHCtafUZOXHdFAAK99JxUfSfmtZYxRCDhPMwrKIDb6ZPXaZO5GHJHtqAMq/IM8pe6vqBYx29Dmxw6qKq6Zu0h3jdDaOByAynzRryqlgqjiNT+4PuUxxqdYYeotKKMXoYiGgE4f8ibi8Q4N1ZDKyCHuhHyLLsN5YvWjBDNzmXSVHvndMarf6h8vUAPHzK4Dc91odeuGV+NKjxj+OJcE9MRO/VzHAlUwzY7aYgIN7tpFeIjn062ndg9CUbjjnf3rhGRybm9gM1uf0sFfLE275p16DaG/43CVZgKmSm+0vqN5P1/UiWpQGPCLA=}
